### ISSUE TITLE
Remove commonly used/unneeded words

### ISSUE THREAD

**Issue by zachtheclimber** [JaZa-Programming/ATS-Hacker#2]
To increase the utility and functionality of ATS-Hacker, I feel we should add the capability to remove commonly used words that are unhelpful to our users. These would be things like "the", "or", "and", "at", "our", etc. Removing these extraneous words allows our users to focus on more important keywords. Perhaps we could even create an external file of words that users could add to or remove from as they see fit.

**Comment by JaimeVRodriguez** [comment]
I agree these words are pretty pointless when trying to find keywords in a job description. Should this be done in the aggregator() function?

**Comment by zachtheclimber** [comment]
I think it makes sense to have the function reside within aggregator.py, since it is closely related, but it should be named something else. Right now, we have this block of code:
```
    removal_characters = ['.', ',', '!', '_', '?', ';']

    for character in removal_characters:
        doc = doc.replace(character, '')
```

We could extract this into its own function (since it is performing an action separate from aggregation) and add another function that takes in a txt file list of words and removes them from the `keywords_dict`after they've been counted (so we aren't iterating over the document multiple times).

I'll go ahead and get started on the tests for these two functions. We can then implement the functions themselves whenever time and interest permits.

**Comment by zachtheclimber** [comment]
Upon a bit more consideration, I think it makes more sense to put the word_removal() function in a separate file under `api` I think. Given how/where we will be calling it, it needs to come out from under the aggregator.

**Comment by zachtheclimber** [comment]
remove_words() is now in a separate file under the `api` folder. Tests are written and ready for a functioning function that functions. :-)

**Comment by ghost** [comment]
This feature is now implemented starting with commit [a62c89](https://github.com/JaZa-Programming/ATS-Hacker/commit/a62c89f753e3605b9b6275d98cd3fd28b318350e)!
